// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using People.Tables.Models;
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Reflection;
using System.Threading;
using System.Threading.Tasks;

namespace People.Tables.Models
{
    public partial interface ITrainingContextProcedures
    {
        Task<int> AddPeopleAsync(IEnumerable<PersonType> people, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> DeletePersonAsync(int? pNo, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<List<GetPeopleResult>> GetPeopleAsync(OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
        Task<int> UpdatePersonAsync(int? pNo, string pFName, string pSName, int? pAge, int? sslcMarks, int? pucMarks, int? beMarks, int? meMarks, string hobby1, string hobby2, string hobby3, OutputParameter<int> returnValue = null, CancellationToken cancellationToken = default);
    }
}
