// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using System;
using System.Data;
using System.Linq;
using System.Threading.Tasks;
using People.Tables.Models;

namespace People.Tables.Models
{
    public partial class TrainingContext
    {

        [DbFunction("GetTotalMarks", "dbo")]
        public static int? GetTotalMarks(int? PNo)
        {
            throw new NotSupportedException("This method can only be called from Entity Framework Core queries");
        }

        protected void OnModelCreatingGeneratedFunctions(ModelBuilder modelBuilder)
        {
        }
    }
}
