// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace People.DataLayer.Models;

public partial class PeopleMark
{
    public int PNo { get; set; }

    public int SslcMarks { get; set; }

    public int PucMarks { get; set; }

    public int? BeMarks { get; set; }

    public int? MeMarks { get; set; }
}