// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace People.DataLayer.Models;

public partial class People
{
    public int PNo { get; set; }

    public string PFName { get; set; }

    public string PSName { get; set; }

    public int PAge { get; set; }
}