// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace People.DataLayer.Models;

public partial class PeopleHobby
{
    public int PNo { get; set; }

    public string Hobby1 { get; set; }

    public string Hobby2 { get; set; }

    public string Hobby3 { get; set; }
}