// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace People.DataLayer.Models
{
    public partial class PersonType
    {
        public int TempId { get; set; }
        [StringLength(100)]
        public string PFName { get; set; }
        [StringLength(100)]
        public string PSName { get; set; }
        public int PAge { get; set; }
        public int SslcMarks { get; set; }
        public int PucMarks { get; set; }
        public int? BeMarks { get; set; }
        public int? MeMarks { get; set; }
        [StringLength(50)]
        public string Hobby1 { get; set; }
        [StringLength(50)]
        public string Hobby2 { get; set; }
        [StringLength(50)]
        public string Hobby3 { get; set; }
    }
}
