// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace People.DataLayer.Models;

public partial class TrainingContext : DbContext
{
    public TrainingContext(DbContextOptions<TrainingContext> options)
        : base(options)
    {
    }

    public virtual DbSet<People> Peoples { get; set; }

    public virtual DbSet<PeopleHobby> PeopleHobbies { get; set; }

    public virtual DbSet<PeopleMark> PeopleMarks { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<People>(entity =>
        {
            entity.HasKey(e => e.PNo);

            entity.Property(e => e.PFName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
            entity.Property(e => e.PSName)
                .IsRequired()
                .HasMaxLength(100)
                .IsUnicode(false);
        });

        modelBuilder.Entity<PeopleHobby>(entity =>
        {
            entity.HasKey(e => e.PNo);

            entity.Property(e => e.PNo).ValueGeneratedNever();
            entity.Property(e => e.Hobby1)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Hobby2)
                .HasMaxLength(50)
                .IsUnicode(false);
            entity.Property(e => e.Hobby3)
                .HasMaxLength(50)
                .IsUnicode(false);
        });

        modelBuilder.Entity<PeopleMark>(entity =>
        {
            entity.HasKey(e => e.PNo);

            entity.Property(e => e.PNo).ValueGeneratedNever();
        });

        OnModelCreatingGeneratedFunctions(modelBuilder);
        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}